### PR TITLE
fix: enable removing access application custom attributes and claims

### LINKED ISSUE #2837: Access application custom attributes don't update when removed
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cloudflare-go version

v0.101.0

### Go environment

```text
GO111MODULE=''
GOARCH='arm64'
GOBIN=''
GOCACHE='/Users/mprovost/Library/Caches/go-build'
GOENV='/Users/mprovost/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/mprovost/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='darwin'
GOPATH='/Users/mprovost/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/opt/homebrew/Cellar/go/1.22.5/libexec'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/opt/homebrew/Cellar/go/1.22.5/libexec/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='go1.22.5'
GCCGO='gccgo'
AR='ar'
CC='cc'
CXX='c++'
CGO_ENABLED='1'
GOMOD='/Users/mprovost/Projects/go-repro/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/zn/gmcgtk3s26xc8x7d4s2z43hw0000gn/T/go-build358138541=/tmp/go-build -gno-record-gcc-switches -fno-common'
```

### Expected output

Custom attributes should be removed when an empty list is passed as the custom attributes.

### Actual output

Nothing changes, since the attribute is omitted when empty:

https://github.com/cloudflare/cloudflare-go/blob/80d52bc4aa257a198d85177a11722407797c9705/access_application.go#L233

### Code demonstrating the issue

```go
package main

import (
	"context"
	"log"
	"os"

	"github.com/cloudflare/cloudflare-go"
)

func main() {
	api, err := cloudflare.New(os.Getenv("CLOUDFLARE_API_KEY"), os.Getenv("CLOUDFLARE_EMAIL"))
	if err != nil {
		log.Fatal(err)
	}

	ctx := context.Background()

	accountId := "<Account ID>"
	applicationId := "<Application ID>"

	account := cloudflare.AccountIdentifier(accountId)

	application := cloudflare.UpdateAccessApplicationParams{
		ID:   applicationId,
		Name: "TESTING",
		Type: "saas",
		SaasApplication: &cloudflare.SaasApplication{
			CustomAttributes: []cloudflare.SAMLAttributeConfig{},
		},
	}

	newApplication, err := api.UpdateAccessApplication(ctx, account, application)
	if err != nil {
		log.Fatal(err)
	}

	log.Print(newApplication)
}
```

### Steps to reproduce

1. Create an Access application
   - Saas type
   - SAML authentication (the application in this step doesn't matter)
   - Add a SAML attribute statement. It doesn't matter the contents, nor any other information in this step
   - The rest of the data is irrelevant and can be set to anything
2. Fill in the repro code with the proper account ID and application ID
3. Run the repro
4. Notice in the dashboard that the custom attribute statement wasn't removed

### References

_No response_

### PR DESCRIPTION
**Pull request by BSFishy**
Removes the `omitempty` on Access application custom attributes. This allows an empty list to be passed to remove empty attributes, which would have otherwise been omitted.

closes #2837

## Description

Removes the `omitempty` on Access application custom attributes.

## Has your change been tested?

Using the script in #2837

## Types of changes

What sort of change does your code introduce/modify?

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] This change is using publicly documented in [cloudflare/api-schemas](https://github.com/cloudflare/api-schemas) 
      and relies on stable APIs.

[1]: https://help.github.com/articles/closing-issues-using-keywords/

### CODE REVIEW

File: access_application.go [hunk 1]
```diff
@@ -230,7 +230,7 @@ type SaasApplication struct {
 	NameIDFormat                  string                `json:"name_id_format,omitempty"`
 	SSOEndpoint                   string                `json:"sso_endpoint,omitempty"`
 	DefaultRelayState             string                `json:"default_relay_state,omitempty"`
-	CustomAttributes              []SAMLAttributeConfig `json:"custom_attributes,omitempty"`
```
Comment (jacobbednarz) [inline access_application.go:233]: if you're doing this, you'll likely want to make it a pointer otherwise, you'll have issues determining empty values.

Comment (BSFishy) [reply access_application.go:233]: Changed 👍 Now it will distinguish between nil and empty as would be expected

**Comment by ajholland** [comment]
Can you do the same thing for the CustomClaims field? - it's the OIDC version of SAML CustomAttributes
