### PR TITLE
Fix not removing tunnel route

### LINKED ISSUE #1029: Cannot remove cloudflare tunnel route which has vnet
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cloudflare-go version

0.46.0

### Go environment

-

### Expected output

Tunnel is removed

### Actual output

No error but tunnel is still present.

### Code demonstrating the issue

-

### Steps to reproduce

1. Create a tunnel route with vnet
2. Remove tunnel route
3. Check via API or web UI whether the tunnel route is still present

### References

https://github.com/cloudflare/terraform-provider-cloudflare/issues/1829

### PR DESCRIPTION
**Pull request by vavsab**
## Description

Fixes https://github.com/cloudflare/cloudflare-go/issues/1029

## Has your change been tested?

All unit tests are green.

## Types of changes

What sort of change does your code introduce/modify?

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x]  My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [ ] This change is using publicly documented (api.cloudflare.com or developers.cloudflare.com) and stable APIs.

### CODE REVIEW

File: tunnel_routes.go [hunk 1]
```diff
@@ -170,7 +170,8 @@ func (api *API) DeleteTunnelRoute(ctx context.Context, rc *ResourceContainer, pa
 		return ErrMissingNetwork
 	}
 
-	uri := fmt.Sprintf("/%s/%s/teamnet/routes/network/%s", AccountRouteRoot, rc.Identifier, url.PathEscape(params.Network))
+	// Cannot fully utilize buildURL here because it tries to escape "%" sign from the already escaped "/" sign from Network field.
```
Comment (jacobbednarz) [inline tunnel_routes.go]:
```suggestion
	// Cannot fully utilize buildURI here because it tries to escape "%" sign
	// from the already escaped "/" sign from Network field.
```

**Comment by jacobbednarz** [comment]
there is an alternative here that allows us to wrap this entire line in `buildURI` however, i'm not convinced this style of URI is something we want to cater for in the 99% of use cases.

```diff
diff --git utils.go utils.go
index 38d4315..39397bc 100644
--- utils.go
+++ utils.go
@@ -12,7 +12,7 @@ import (
 // buildURI assembles the base path and queries.
 func buildURI(path string, options interface{}) string {
        v, _ := query.Values(options)
-       return (&url.URL{Path: path, RawQuery: v.Encode()}).String()
+       return path + (&url.URL{RawQuery: v.Encode()}).String()
 }

 // loadFixture takes a series of path components and returns the JSON fixture at
diff --git utils_test.go utils_test.go
index 5973d8c..30f7a02 100644
--- utils_test.go
+++ utils_test.go
@@ -27,11 +27,14 @@ func Test_buildURI(t *testing.T) {
                "single level path with params":          {path: "/bar", params: testExample{C: "d"}, want: "/bar?c=d"},
                "single level path with multiple params": {path: "/foo", params: testExample{A: "b", C: "d"}, want: "/foo?a=b&c=d"},
                "single level path with nested fields":   {path: "/foo", params: testExample{A: "b", C: "d", PaginationOptions: PaginationOptions{PerPage: 10}}, want: "/foo?a=b&c=d&per_page=10"},
+               "escaped URL path":                       {path: "/foo/10.0.0.0%2F1", params: testExample{A: "b", C: "d"}, want: "/foo/10.0.0.0%2F1?a=b&c=d"},
+               "unescaped URL path":                     {path: "/foo/10.0.0.0/1", params: testExample{A: "b", C: "d"}, want: "/foo/10.0.0.0/1?a=b&c=d"},
        }

        for name, tc := range tests {
                t.Run(name, func(t *testing.T) {
                        got := buildURI(tc.path, tc.params)
+
                        assert.Equal(t, tc.want, got)
                })
        }
```

File: utils.go [hunk 2]
```diff
@@ -12,7 +12,7 @@ import (
 // buildURI assembles the base path and queries.
 func buildURI(path string, options interface{}) string {
 	v, _ := query.Values(options)
-	return (&url.URL{Path: path, RawQuery: v.Encode()}).String()
+	return path + (&url.URL{RawQuery: v.Encode()}).String()
```
Comment (jacobbednarz) [inline utils.go]: sorry, my comment must not have been clear. i'm still not sure if we want to do this; it was more of a discussion point. i'm looking into the drawbacks before we swap everything over given most methods use this now and i wouldn't want to make `buildURI` less robust for this single (sad) URL.

Comment (vavsab) [reply utils.go]: Ok. Let's do it in a safe way.

Comment (vavsab) [reply utils.go]: Definitely changing buildURI may lead to unpredictable bugs in other places

**Comment by jacobbednarz** [comment]
thanks!
