### PR TITLE
Remove double-unmarshalling

### LINKED ISSUE #1045: Double-unmarshalling of `config` from cfd_tunnel/{{TUNNEL_ID}}/configurations is unnecessary
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cloudflare-go version

0.46.0

### Go environment

Not relevant.

### Expected output

I was expecting to use `GetTunnelConfiguration` and `UpdateTunnelConfiguration`.
However, it seems like those methods are no longer compatible with the latest version of the API at https://api.cloudflare.com/#cloudflare-tunnel-configuration-properties

I traced the error down to the double-marshaling that was done in https://github.com/cloudflare/cloudflare-go/pull/948#issuecomment-1166701661.

### Actual output

Error unmarshalling.

`2022/08/16 12:38:25 Failed to get config for current tunnel: error unmarshalling the JSON response: json: cannot unmarshal object into Go struct field TunnelConfigurationStringifiedConfigResult.result.config of type string`

### Code demonstrating the issue

	// Get the current configuration
	currentConfig, err := api.GetTunnelConfiguration(ctx, cloudflare.AccountIdentifier(accountId), tunnelId)
	if err != nil {
		if _, ok := err.(*cloudflare.NotFoundError); ok {
			shouldCreateFromScratch = true
		} else {
			log.Fatal("Failed to get config for current tunnel: ", err)
		}
	}

### Steps to reproduce

1. Create a sample go project that uses v0.46.0 of the API.
2. Ensure that you have Cloudflare Tunnel with a Cloudflare Tunnel Configuration.
3. Attempt to get/update the tunnel configuration
4. Notice the serialization error

### References

https://github.com/cloudflare/cloudflare-go/pull/948#issuecomment-1166701661

### PR DESCRIPTION
**Pull request by vazexqi**
## Description

Fixes #1045 

## Has your change been tested?

Modified existing tests and ran `go test`.

## Types of changes

What sort of change does your code introduce/modify?

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] This change is using publicly documented (api.cloudflare.com or developers.cloudflare.com) and stable APIs.

[1]: https://help.github.com/articles/closing-issues-using-keywords/

### CODE REVIEW

File: tunnel.go [hunk 1]
```diff
@@ -320,31 +320,20 @@ func (api *API) UpdateTunnelConfiguration(ctx context.Context, rc *ResourceConta
 	}
 
 	uri := fmt.Sprintf("/accounts/%s/cfd_tunnel/%s/configurations", rc.Identifier, params.TunnelID)
-	res, err := api.makeRequestContext(ctx, http.MethodPut, uri, params.Config)
```
Comment (vazexqi) [inline tunnel.go:323]: This is a slightly different bug but also has to do with the marshalling/unmarshalling of the `config` param.

**Comment by vazexqi** [comment]
I am new to this process so let me know if there's anything that I'm missing.
In the mean time, I am using my forked version at https://github.com/zuplo/cloudflare-go to unblock myself.

**Comment by jacobbednarz** [comment]
let me confirm with the service team as this was the correct API response when it was added.

File: tunnel.go [hunk 2]
```diff
@@ -73,9 +73,9 @@ type TunnelConnectionResponse struct {
 // other than in the HTTP response unmarshaling. Use `TunnelConfigurationResult`
 // for the correct types.
 type TunnelConfigurationStringifiedConfigResult struct {
```
Comment (jacobbednarz) [inline tunnel.go]: this should be renamed now to better reflect it's use

Comment (vazexqi) [reply tunnel.go]: I think it can be removed now (see my latest PR).

I think this is OK. It's not safe since it can be breaking because `TunnelConfigurationStringifiedConfigResult` was an exported type before in the SDK but I doubt anyone was directly referencing those types.

**Comment by jacobbednarz** [comment]
this still needs a CHANGELOG too

File: .changelog/1046.txt [hunk 3]
```diff
@@ -0,0 +1,3 @@
+```release-note:bug
+TunnelConfiguration: Remove unnecessary double-unmarshalling due to changes in https://api.cloudflare.com/#cloudflare-tunnel-configuration-properties
```
Comment (jacobbednarz) [inline .changelog/1046.txt]:
```suggestion
tunnel_configuration: Remove unnecessary double-unmarshalling due to changes in the API
```

**Comment by jacobbednarz** [comment]
thanks for getting this over the line 🎉

**Comment by vazexqi** [comment]
@jacobbednarz - Thanks for helping with this PR. Do you know when you will cut a new release so that I can switch over to the official version instead of my fork?

**Comment by jacobbednarz** [comment]
details in https://github.com/cloudflare/cloudflare-go/blob/master/docs/release-process.md. 

you can also check the milestone that this PR was added to.
