### PR TITLE
fix(dns): keep comments intact with zero values of UpdateDNSRecordParams

### LINKED ISSUE #1371: Zero values of UpdateDNSRecordParams should keep the comments
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the library and it is still present.

### cloudflare-go version

0.75

### Go environment

N/A

### Expected output

Previously, the Go interface will keep the original comments because of `omitempty`. It's not ideal because there's no easy way to clear comments, where an empty string will keep the original comment because `omitempty` will omit empty strings. The API has since then changed to clear comments when an empty string is used, and the Go library was updated, but then one cannot easily keep the current comments. I believe the expected behavior of `Update` with zero values is to keep everything, and using strings cannot distinguish the two important cases: (1) keep the current comment and (2) clear the current comment.

Suggested solution: use `*string` for the `Comment` field and add back `omitempty`.

### Actual output

See above

### Code demonstrating the issue

```go
// This will clear the comments
c.UpdateDNSRecord(ctx, ZoneIdentifier(zone), UpdateDNSRecordParams{
		ID:      id,
		Content: ip,
	}
)
```

### Steps to reproduce

See above

### References

- https://github.com/cloudflare/cloudflare-go/pull/1166
- https://github.com/cloudflare/cloudflare-go/pull/1194

### PR DESCRIPTION
**Pull request by favonia**
## Description

Calling `UpdateDNSRecord` with an (almost) zero value of `UpdateDNSRecordParams` will cause the existing comments to be erased. The solution is straightforward---change the type of the field `Comment` from `string` to `&string`, just like how the field `Proxy` has the type `&bool` instead of `bool`.

Closes #1371.

## Has your change been tested?

Yes, but the test must be done against the real server. It is difficult to include a real test in the Go library.

## Types of changes

What sort of change does your code introduce/modify?

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes. **CAVEAT: A real test can only be done against the real API server, not against the mock server within the Go library.**
- [x] All new and existing tests passed.
- [x] This change is using publicly documented in [cloudflare/api-schemas](https://github.com/cloudflare/api-schemas) 
      and relies on stable APIs.

### CODE REVIEW

File: dns_test.go [hunk 1]
```diff
@@ -476,7 +477,7 @@ func TestGetDNSRecord(t *testing.T) {
 			"auto_added": true,
 			"source":     "primary",
 		},
-		Comment: "This is a comment",
+		Comment: &comment,
```
Comment (jacobbednarz) [inline dns_test.go]: we can use [`StringPtr`](https://github.com/cloudflare/cloudflare-go/blob/master/convert_types.go#L571) to simplify this here

File: dns_test.go [hunk 2]
```diff
@@ -567,9 +568,10 @@ func TestUpdateDNSRecord_ClearComment(t *testing.T) {
 	setup()
 	defer teardown()
 
+	emptyComment := ""
 	input := DNSRecord{
 		ID:      "372e67954025e0ba6aaa6d586b9e0b59",
-		Comment: "",
+		Comment: &emptyComment,
```
Comment (jacobbednarz) [inline dns_test.go]: similar to https://github.com/cloudflare/cloudflare-go/pull/1393/files#r1320954470

**Comment by jacobbednarz** [comment]
did you manually confirm these API calls are working for your use case on the PATCH endpoint? this lgtm

**Comment by favonia** [comment]
@jacobbednarz Thanks for the reminder. I did the tests about `GetDNSRecord`, `UpdateDNSRecord` and `ListDNSRecords` (but not `CreateDNSRecord`), and added some comments. (I actually made some mistake but the manual testing got it.) I decided to keep the type of the `Comment` field in `DNSRecord`, `ListDNSRecordsParams` and `CreateDNSRecordParams` as `string` (reverting my earlier commit in this PR), only changing that of `UpdateDNSRecordParams` to `&string`. The reason is that the server would omit the empty comment field when returning the results. I hope such inconsistency is okay.

**Comment by jacobbednarz** [comment]
> I hope such inconsistency is okay.

it is! and it only that, this is a shining example of where the CRUD operation specific params for a method allow us to make isolated changes without breaking all the method usages at once.

**Comment by favonia** [comment]
@jacobbednarz Personally I think this is ready to go!

**Comment by jacobbednarz** [comment]
thank you!
